gin:
  port: ":4000"
  host: ""

grpc-client:
  services:
    - name: "auth_service"
      port: ":5101"
      host: "auth-service"
    - name: "token_service"
      port: ":5102"
      host: "token_service"